export const COMMON_COLLEGES: string[] = [
  "Amherst College",
  "Arizona State University",
  "Babson College",
  "Barnard College",
  "Bates College",
  "Baylor University",
  "Boston College",
  "Boston University",
  "Bowdoin College",
  "Brandeis University",
  "Brown University",
  "Bucknell University",
  "California Institute of Technology",
  "Carleton College",
  "Carnegie Mellon University",
  "Case Western Reserve University",
  "Claremont McKenna College",
  "Colby College",
  "Colgate University",
  "Colorado College",
  "Columbia University",
  "Cornell University",
  "Dartmouth College",
  "Davidson College",
  "Duke University",
  "Emory University",
  "Florida State University",
  "George Washington University",
  "Georgetown University",
  "Georgia Institute of Technology",
  "Hamilton College",
  "Harvard University",
  "Harvey Mudd College",
  "Haverford College",
  "Indiana University Bloomington",
  "Johns Hopkins University",
  "Lehigh University",
  "Macalester College",
  "Massachusetts Institute of Technology",
  "Middlebury College",
  "New York University",
  "North Carolina State University",
  "Northeastern University",
  "Northwestern University",
  "Oberlin College",
  "Ohio State University",
  "Pennsylvania State University",
  "Pitzer College",
  "Pomona College",
  "Princeton University",
  "Purdue University",
  "Rice University",
  "Rutgers University",
  "Scripps College",
  "Smith College",
  "Stanford University",
  "Swarthmore College",
  "Texas A&M University",
  "Trinity College",
  "Tufts University",
  "Tulane University",
  "University of California, Berkeley",
  "University of California, Davis",
  "University of California, Irvine",
  "University of California, Los Angeles",
  "University of California, San Diego",
  "University of California, Santa Barbara",
  "University of Chicago",
  "University of Florida",
  "University of Georgia",
  "University of Illinois Urbana-Champaign",
  "University of Maryland, College Park",
  "University of Michigan",
  "University of North Carolina at Chapel Hill",
  "University of Notre Dame",
  "University of Pennsylvania",
  "University of Pittsburgh",
  "University of Rochester",
  "University of Southern California",
  "University of Texas at Austin",
  "University of Virginia",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Vanderbilt University",
  "Vassar College",
  "Villanova University",
  "Wake Forest University",
  "Washington and Lee University",
  "Washington University in St. Louis",
  "Wellesley College",
  "Wesleyan University",
  "Williams College",
  "Yale University",
];
